baseURL = "https://mehuse.xyz/"
languageCode = "de"
defaultContentLanguage = "de"
title = "Out And About"
theme = "PaperMod"

[params]
  mainSections = ["posts"]

[params.assets]
  favicon = "icons/favicon-32x32.png"
  favicon16x16 = "icons/favicon-16x16.png"
  favicon32x32 = "icons/favicon-32x32.png"
  apple_touch_icon = "icons/apple-touch-icon.png"
  # safari_pinned_tab = "icons/safari-pinned-tab.svg"

[[menus.main]]
name = "Wohin"
url = "/wohin/"
weight = 10
