baseURL = "https://mehuse.xyz/"
languageCode = "de"
defaultContentLanguage = "de"
title = "Unterwegs"
theme = "PaperMod"

[params]
  mainSections = ["posts"]

[[menus.main]]
name = "Wohin"
url = "/wohin/"
weight = 10
