baseURL = "https://mehuse.xyz/"
languageCode = "de"
defaultContentLanguage = "de"
title = "Unterwegs"
theme = "PaperMod"

[params]
  mainSections = ["posts"]

[[menus.main]]
name = "Wunschliste"
url = "/wishlist/"
weight = 10
