backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "static/images"
public_folder: "/images"
output_format: toml
extension: md

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Cover"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - { label: "Image", name: "image", widget: "image", required: false, hint: "Recommended: compress images to under 500KB" }
          - { label: "Alt text", name: "alt", widget: "string", required: false }
          - { label: "Caption", name: "caption", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }